name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Load Nix caches
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Run checks
        run: nix flake check

      - name: Buid and verify PDFs are up to date
        run: nix run .#pdf-check