name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Load Nix caches
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Run checks
        run: nix flake check

      - name: Build CV
        run: |
          nix develop --command tectonic -X build
          cp build/Daniel_Palencia_Resume/Daniel_Palencia_Resume.pdf /tmp/Daniel_Palencia_Resume.pdf
          rm -rf build/ .tectonic/
          nix develop --command tectonic -X build
          cp build/Daniel_Palencia_CV/Daniel_Palencia_CV.pdf /tmp/Daniel_Palencia_CV.pdf

      - name: Compare with committed PDF
        run: nix run .#pdf-check